USE zapdb;

CREATE TABLE `users` (
  `user_name` VARCHAR(100) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  `user_id` INT(11) NULL,
  `license_id` VARCHAR(100) NULL,
  PRIMARY KEY (`user_name`)
) ENGINE=InnoDB;

CREATE TABLE `user_role` (
  `user_name` VARCHAR(100) NOT NULL,
  `role_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`user_name`, `role_name`),
  CONSTRAINT zap_ur_username_fk FOREIGN KEY (`user_name`) REFERENCES `users` (`user_name`) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE `participant` (
  `participant_id` VARCHAR(100) NOT NULL,
  `participant_name` VARCHAR(100) NULL,
  `email_id` TEXT NULL,
  `license_id` VARCHAR(100) NULL,
  `organization_number` VARCHAR(100) NULL,
  `send_email` TINYINT(1) NULL,
  PRIMARY KEY (`participant_id`)
) ENGINE=InnoDB;

CREATE TABLE `user_participant` (
  `user_name` VARCHAR(100) NOT NULL,
  `participant_id` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`user_name`, `participant_id`),
  CONSTRAINT zap_up_username_fk FOREIGN KEY (`user_name`) REFERENCES `users` (`user_name`) ON DELETE CASCADE,
  CONSTRAINT zap_up_participantid_fk FOREIGN KEY (`participant_id`) REFERENCES `participant` (`participant_id`) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE `accesspoint_settings` (
   `accesspoint_id` VARCHAR(100) NOT NULL,
   `last_sync_datetime` DATETIME NULL,
   PRIMARY KEY (`accesspoint_id`)
) ENGINE=InnoDB;

CREATE TABLE `audit_log` (
  `audit_log_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `event_id` VARCHAR(250) NOT NULL,
  `event_type` VARCHAR(100) NULL,
  `sender_id` VARCHAR(100) NULL,
  `receiver_id` VARCHAR(100) NULL,
  `user_id` VARCHAR(100) NULL,
  `license_id` VARCHAR(100) NULL,
  `description` VARCHAR(100) NULL,
  `event_date` DATETIME NULL,
  `status` TINYINT(1) UNSIGNED NULL,
  `comments` TEXT NULL,
  `file_content` LONGBLOB NULL,
  PRIMARY KEY (`audit_log_id`),
  KEY `zap_al_eventid_idx` (`event_id`),
  KEY `zap_al_senderid_idx` (`sender_id`),
  KEY `zap_al_receiverid_idx` (`receiver_id`),
  KEY `zap_al_licenseid_idx` (`license_id`)
) ENGINE=InnoDB;

CREATE TABLE `peppol_message_meta_data` (
	`PEPPOL_MESSAGE_META_DATA_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`AUDIT_LOG_ID` INT(10) UNSIGNED NULL DEFAULT NULL,
	`MESSAGE_FILE_NAME` VARCHAR(100) NULL DEFAULT NULL,
	`MESSAGE_IDENTIFIER` VARCHAR(100) NOT NULL,
	`RECIPIENT_IDENTIFIER` VARCHAR(100) NOT NULL,
	`RECIPIENT_SCHEME_ID` VARCHAR(100) NULL DEFAULT NULL,
	`SENDER_IDENTIFIER` VARCHAR(100) NOT NULL,
	`SENDER_SCHEME_ID` VARCHAR(100) NULL DEFAULT NULL,
	`DOCUMENT_TYPE_IDENTIFIER` VARCHAR(1000) NULL DEFAULT NULL,
	`PROFILE_TYPE_IDENTIFIER` VARCHAR(1000) NULL DEFAULT NULL,
	`SENDING_ACCESS_POINT` VARCHAR(100) NULL DEFAULT NULL,
	`RECEIVING_ACCESS_POINT` VARCHAR(100) NULL DEFAULT NULL,
	`PROTOCOL` VARCHAR(100) NULL DEFAULT NULL,
	`USER_AGENT` VARCHAR(100) NULL DEFAULT NULL,
	`USER_AGENT_VERSION` VARCHAR(100) NULL DEFAULT NULL,
	`SENDERS_TIME_STAMP` DATETIME NULL DEFAULT NULL,
	`RECEIVED_TIME_STAMP` DATETIME NULL DEFAULT NULL,
	`SENDING_ACCESS_POINT_PRINCIPAL` VARCHAR(100) NULL DEFAULT NULL,
	`TRANSMISSION_ID` VARCHAR(100) NULL DEFAULT NULL,
	`BUILD_USER` VARCHAR(100) NULL DEFAULT NULL,
	`BUILD_DESCRIPTION` VARCHAR(100) NULL DEFAULT NULL,
	`BUILD_TIME_STAMP` VARCHAR(100) NULL DEFAULT NULL,
	`MESSAGE_READ_FLAG` TINYINT(1) NOT NULL,
	`READ_FROM_WEB` TINYINT(1) UNSIGNED NULL DEFAULT NULL,
	`OXALIS` VARCHAR(100) NULL DEFAULT NULL,
	`IS_DELETED` TINYINT(1) NULL DEFAULT NULL,
	`FILE_CONTENT` LONGBLOB NULL,
	`FILE_PATH` VARCHAR(100) NULL DEFAULT '0',
	PRIMARY KEY (`PEPPOL_MESSAGE_META_DATA_ID`),
	INDEX `FK_AUDIT_LOG_ID` (`AUDIT_LOG_ID`),
	INDEX `INX_RECIPIENT_IDENTIFIER` (`RECIPIENT_IDENTIFIER`),
	INDEX `INX_RECEIVED_TIME_STAMP` (`RECEIVED_TIME_STAMP`),
	INDEX `INX_MESSAGE_READ_FLAG` (`MESSAGE_READ_FLAG`),
	INDEX `INX_MESSAGE_IDENTIFIER` (`MESSAGE_IDENTIFIER`),
	INDEX `INX_IS_DELETED` (`IS_DELETED`),
	INDEX `INX_SENDER_IDENTIFIER` (`SENDER_IDENTIFIER`),
	CONSTRAINT `FK_AUDIT_LOG_ID` FOREIGN KEY (`AUDIT_LOG_ID`) REFERENCES `audit_log` (`audit_log_id`) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE `transaction_details` (
	`TXN_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`AUDIT_LOG_ID` INT(10) UNSIGNED NOT NULL,
	`INVOICE_STATUS` INT(10) UNSIGNED NOT NULL,
	`CREATED_BY` VARCHAR(100) NULL DEFAULT NULL,
	`CREATED_DATETIME` DATETIME NOT NULL,
	PRIMARY KEY (`TXN_ID`),
	INDEX `index_audit_log_id` (`AUDIT_LOG_ID`),
	INDEX `index_invoice_status` (`INVOICE_STATUS`),
	INDEX `index_main` (`AUDIT_LOG_ID`, `INVOICE_STATUS`)
) ENGINE=InnoDB;

CREATE TABLE `transaction_status` (
	`TXN_STATUS_ID` INT(10) UNSIGNED NOT NULL,
	`TXN_STATUS_NAME` VARCHAR(50) NOT NULL,
	PRIMARY KEY (`TXN_STATUS_ID`)
) ENGINE=InnoDB;
